<a href="https://colab.research.google.com/github/DanileRond/learning_datasets/blob/master/working_textdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## One-Hot codding per al ús de 'Tensors' (Treballant amb text Tensorflow-Keras) 

In [0]:
import numpy as np


In [0]:
samples = ['The cat sat on the mat.', 'The dog ate my homework.']

In [0]:
token_index = {}
for sample in samples: 
    for word in sample.split():
        if word not in token_index:
            token_index[word] = len(token_index) + 1
max_length = 10



In [0]:
results = np.zeros(shape=(len(samples),
                          max_length,
                          max(token_index.values()) + 1))
for i, sample in enumerate(samples):
  for j, word in list(enumerate(sample.split())) [:max_length]:
    index = token_index.get(word)
    results[i,j,index] = 1.

In [0]:
print(results)

[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


Una matriu per mostra. A cada mostra tenim 'n' paraules o tokens. Sample(1) te 6 paraules i Sample(2) 5. Fixat en la continuitat del diccionari en la matriu 2 i el mateix valor de vector per a la fila 1, paraula The.

In [0]:
token_index['cat']

2

In [0]:
print(token_index)

{'The': 1, 'cat': 2, 'sat': 3, 'on': 4, 'the': 5, 'mat.': 6, 'dog': 7, 'ate': 8, 'my': 9, 'homework.': 10}


# One-Hot amb Keras
Keras proporciona eines per realitzar el procés anterior de forma més fàcil i ràpida

In [0]:
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [0]:
samples

['The cat sat on the mat.', 'The dog ate my homework.']

In [0]:
tokenizer = Tokenizer(num_words=1000)

In [0]:
tokenizer.fit_on_texts(samples)

In [0]:
sequences = tokenizer.texts_to_sequences(samples)

In [0]:
one_hot_results = tokenizer.texts_to_matrix(samples, mode='binary')

In [0]:
word_index=tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

Found 9 unique tokens.


## Ús de Word Embeddings (Embotir paraules)

Per treballar amb tensors que continguin informació de text, no arriba a ser cómode el one-hot. Si ens fixem,el resultat d'aquesta organització són uns vectors molt extens amb un gran volum de 0's. Per tant busquem comprimir en vectors més densos la informació. Aquests vectors es crean i optimitzen buscant relacionar les paraules segons cert significat amb el que treballar. Per exemple: Vector 'Femení' va de la paraula King a Queen. Vector 'Plural' de King a Kings, etc. Aixó crea diccionaris més densos i capaços d'estalivar espai en els vectors anteriors. La manera en que es crean, és a partir de tècniques de backpropagation que podem realitzar a partir de keras. A continuació es veu un exemple amb una bdd de IMDB.

In [0]:
from keras.layers import Embedding

In [0]:
embedding_layer = Embedding(1000, 64)

In [0]:
from keras.datasets import imdb

In [0]:
from keras import preprocessing

In [0]:
max_features = 10000
maxlen = 20

In [0]:
(x_train,y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

17465344/17464789 [==============================] - 1s 0us/step


In [0]:
x_train = preprocessing.sequence.pad_sequences(x_train, maxlen=maxlen)

In [0]:
x_test = preprocessing.sequence.pad_sequences(x_test, maxlen=maxlen)

In [0]:
from keras.models import Sequential

In [0]:
from keras.layers import Flatten, Dense

In [0]:
model = Sequential()
model.add(Embedding(10000, 8, input_length=maxlen))
model.add(Flatten())

In [0]:
model.add(Dense(1,activation='sigmoid'))

In [0]:
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['acc'])

In [0]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 8)             80000     
_________________________________________________________________
flatten_1 (Flatten)          (None, 160)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 161       
Total params: 80,161
Trainable params: 80,161
Non-trainable params: 0
_________________________________________________________________


In [0]:
history = model.fit(x_train,y_train, epochs=10,batch_size=32,validation_split=0.2)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 3s 166us/step - loss: 0.6687 - acc: 0.6166 - val_loss: 0.6150 - val_acc: 0.7030
Epoch 2/10
20000/20000 [==============================] - 2s 79us/step - loss: 0.5373 - acc: 0.7516 - val_loss: 0.5226 - val_acc: 0.7338
Epoch 3/10
20000/20000 [==============================] - 2s 81us/step - loss: 0.4603 - acc: 0.7861 - val_loss: 0.5004 - val_acc: 0.7476
Epoch 4/10
20000/20000 [==============================] - 2s 83us/step - loss: 0.4245 - acc: 0.8075 - val_loss: 0.4948 - val_acc: 0.7560
Epoch 5/10
20000/20000 [==============================] - 2s 80us/step - loss: 0.4008 - acc: 0.8198 - val_loss: 0.4953 - val_acc: 0.7570
Epoch 6/10
20000/20000 [==============================] - 2s 81us/step - loss: 0.3816 - acc: 0.8288 - val_loss: 0.4983 - val_acc: 0.7600
Epoch 7/10
20000/20000 [==============================] - 2s 81us/step - loss: 0.3649 - acc: 0.8386 - val_loss: 0.5042 - val_acc

### Using Pretrained Word Embeddings

In [0]:
import os

imdb_dir = '/My Drive/aclImdb'
train_dir = os.path.join(imdb_dir,'train')

labels = []
texts = []

for label_type in ['neg','pos']:
  dir_name = os.path.join(train_dir, label_type)
  for fname in os.listdir(dir_name):
    if fname[-4:] == '.txt':
      f = open(os.path.join(dir_name,fname))
      texts.append(f.read())
      f.close()
      if label_type == 'neg':
        labels.append(0)
      else:
        labels.append(1)

In [0]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np

maxlen = 100
training_samples = 200
validation_samples = 10000
max_words = 10000

tokenizer = Tokenizer(num_words = max_words)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

data = pad_sequences(sequences, maxlen=maxlen)

labels = np.asarray(labels)
print('Shape of data tensor.' data.shape)
print('Shape of label tensor.' labels.shape)

indices = np.arange(data.shape[0])
np.random.shuffle(indices)
data = data[indices]
labels = labels[indices]

x_train = data[:training_samples]
y_train = labels[:training_samples]

x_val = data[training_samples: training_samples + validation_samples]
y_val = labels[training_samples: training_samples + validation_samples]

#Ara anem a descarregar les word embeddings de la basede dades de GloVe.

In [0]:
glove_dir = 'glove.6B'

# RNN
